# Mod Properties
mod_id=thermal
mod_name=Thermal Core
mod_version=11.0.7

# Gradle Properties
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Platform Properties
java_version=25
mc_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.109

# Dependency Properties
cofh_core_version=11.0.2
cofh_core_max_version=11.1.0

jei_version=29.40.0.101
curios_version=15.0.0+26.1.2
patchouli_version=26.1-94

# Publishing Properties

# Options: alpha, beta, release
release_type=release